accounts/urls.py
from django.urls import path, include
from accounts import views
from django.contrib.auth.models import User

app_name = 'accounts'

urlpatterns = [
    #path('', views.signup_view, name="account-main"),
    #path('<str:username>', views.account, name="account"),
    path('login/', views.login_view, name="login"),
    #path('signup/', views.signup_view, name="signup"),
    #path('staff_signup/', views.staffsignup_view, name="staff_signup"),
    path('logout/', views.logout_view, name="logout"),
    #path('update/', views.account_update, name="account_update")

]

ccith_admon/urls.py
from django.contrib import admin
from django.urls import path, include
from ccith_admon import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.solicitud, name="solicitud"),
    path('registrar_solicitante/', views.registrar_solicitante, name="add_solicitante"),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('exportar_csvs_registros/', views.exportar_csv_registros, name="exportar_csv_registros"),
    path('exportar_csvs_solicitantes/', views.exportar_csv_solicitantes, name="exportar_csv_solicitantes"),
    #path('devolucion/<id>', views.devolucion, name="devolucion"),
    #path('marcar_incidencia/<id>', views.marcar_incidencia, name="marcar_incidencia"),
    #path('proyectores/', views.status_proyectores, name="proyectores"),
    #path('proyector_status_update/<id>', views.proyector_status_update, name="proyector_status_update"),
    #path('solicitantes/', views.solicitantes, name="solicitantes"),
    #path('bloquear_solicitante/<id>', views.bloquear_solicitante, name="bloquear_solicitante")
]

ccith_admon/models.py
import os
from datetime import datetime, timedelta
#from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin 
#from django.contrib.auth.base_user import BaseUserManager
from django.db import models

class Solicitante(models.Model):
    matricula = models.CharField(max_length=10, blank=False, primary_key=True, unique=True)
    nombre = models.CharField(max_length=20, blank=False)
    ap_pat = models.CharField(max_length=20, blank=True, null=True)
    ap_mat = models.CharField(max_length=20, blank=True, null=True)
    carrera = models.CharField(max_length=30, blank=True, null=True)
    #bloqueado = models.BooleanField(default=False)

    def __str__(self):
        return self.matricula

class Registro(models.Model):
    RAZON_USO_CHOICES=(
        ('TAREA', 'Tarea'),
        ('ESTUDIO', 'Estudio'),
        ('INVESTIGACION', 'Investigación'),
    )
    
    solicitante = models.ForeignKey(Solicitante, default=None, on_delete=models.CASCADE)
    fecha_hora = models.DateTimeField(blank=True, null=True)
    razon_uso = models.CharField(max_length=20, choices=RAZON_USO_CHOICES, default="TAREA")
   

    def __str__(self):
        return "Prestamo " + str(self.id)

ccith_admon/forms.py
from django.db import models
from django import forms
from .models import Registro, Solicitante
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator

class RegistroCC_Form(forms.ModelForm):
    required_css_class = 'required'
    def clean_solicitante(self):
        solicitante = self.cleaned_data.get('solicitante')
        try:
            Solicitante.objects.get(matricula=solicitante)
        except Solicitante.DoesNotExist:
            msg = forms.ValidationError('Matricula no existente en el sistema.')
            self.add_error('solicitante', msg)
            raise msg
        return solicitante

    class Meta:
        model = Registro
        fields = ['solicitante', 'razon_uso']
        labels = {
            'razon_uso': 'Razón de uso'
        }

class RegistroSolicitante_Form(forms.ModelForm):
    required_css_class = 'required'
    def clean_matricula(self):
        matricula = self.cleaned_data.get('matricula').upper()
        r = Solicitante.objects.filter(matricula=matricula)
        if r.count():
            raise ValidationError("Matricula ya existente")
        return matricula

    def clean_carrera(self):
        carrera = self.cleaned_data.get('carrera').upper()
    class Meta:
        model = Solicitante
        fields = ['matricula', 'nombre', 'ap_pat', 'ap_mat', 'carrera']
        labels = {
            'matricula' : 'No. Control',
            'ap_pat' : 'Apellido Paterno',
            'ap_mat' : 'Apellido Materno'
        }

ccith_admon/views.py
import datetime
import csv
from datetime import date, timedelta
from django.db.models import Count
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib import messages
from .models import Registro, Solicitante
from .forms import RegistroCC_Form, RegistroSolicitante_Form
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required, permission_required

@login_required(login_url="/ccith_admon/accounts/login/")
def dashboard(request):
    today = timezone.now()
    registros = Registro.objects.all()

    return render(request, 'dashboard.html', {'registros':registros})


def solicitud(request):

   
    if request.method == 'POST':
        try:
            solicitante = Solicitante.objects.get(matricula=request.POST.get('solicitante'))
        except Solicitante.DoesNotExist:
            messages.error(request, mark_safe('No. de Control '+str(request.POST.get('solicitante')) + ' no existente en el sistema. <strong>Verifique que lo haya ingresado correctamente</strong> o <a href="/ccith_admon/registrar_solicitante/">Registrese aquí</a>'))
            return redirect('solicitud')
        form = RegistroCC_Form(request.POST)
        if form.is_valid():
            solicitud = form.save(commit=False)
            
            solicitud.fecha_hora=timezone.now()
            solicitud.save()
            messages.success(request, 'Aprobada')
            return redirect('solicitud')
    else:
        form = RegistroCC_Form()
    
    return render(request, 'solicitud.html', { 'form': form})

def registrar_solicitante(request):
    if request.method == 'POST':
        form = RegistroSolicitante_Form(request.POST)

        if form.is_valid():
            messages.success(request, 'Solicitante Registrado Correctamente')
            instance = form.save(commit=False)
            instance.save()
            return redirect('solicitud')
        else:
            messages.error(request, 'Error al Registrar')
    else:
        form = RegistroSolicitante_Form()

    return render(request, 'add_solicitante.html', {'form': form})

def exportar_csv_registros(request):

    output = []
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment;filename="CC_registros_data.csv"'

    writer = csv.writer(response)
    query_set = Registro.objects.all()
    writer.writerow(['id', 'Solicitante', 'fecha_hora', 'razon_uso'])
    for registro in query_set:
        output.append([registro.id, registro.solicitante, registro.fecha_hora, registro.razon_uso])
    writer.writerows(output)
    return response

def exportar_csv_solicitantes(request):

    output = []
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment;filename="CC_solicitantes_data.csv"'

    writer = csv.writer(response)
    query_set = Solicitante.objects.all()
    writer.writerow(['No. Control', 'Nombre', 'Apellido_Paterno', 'Apellido_Materno', 'Carrera'])
    for solicitante in query_set:
        output.append([solicitante.matricula, solicitante.nombre, solicitante.ap_pat, solicitante.ap_mat, solicitante.carrera])
    writer.writerows(output)
    return response










    
        

ccith_admon/templates/add_solicitante.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load bootstrap %}

{% block subtitle %}
Registrar Solicitante
{% endblock %}

{% block styles %}

{% endblock %}

{% block nav %}

{% include 'dash_navbar.html' %}

{% endblock %}



{% block content %}

{% block messages %}
  {% include 'messages.html' %}
{% endblock %}

<div class="container mb-3 d-flex justify-content-between align-items-center">
    <h1 class="mb-3"> Registrar Solicitante </h1>
  </div>

<form action="{% url 'add_solicitante' %}" method="post">
{% csrf_token %}
{{ form|bootstrap }}

<div class="container mb-3 d-flex justify-content-between align-items-center">
    
    
    <a class="btn btn-secondary" href="{% url 'solicitud' %}" role="button">Cancelar</a>
    <button type="submit" class="btn btn-warning">Registrar</button>
  
  </div>



</form>

{% endblock %}

{% block scripts %}

{% endblock %}

ccith_admon/templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block subtitle %} {% endblock %} - {{ project_name }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!--<link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">--->
    <link rel="stylesheet" href="{% static '/css/styles.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static '/plugins/datetimepicker/build/css/tempusdominus-bootstrap-4.min.css' %}">

    <link href="https://unpkg.com/ionicons@4.5.5/dist/css/ionicons.min.css" rel="stylesheet">
    <style>
     #content-body{
    padding-top: 40px !important;
  }

  #header-global{
    text-decoration: none;
  }

    </style>
    {% block styles %}
  
    {% endblock %}
</head>
<body>
        <header class="topbar bg-info">
                <div class="container">
                  <div class="flex-row d-flex justify-content-between align-items-center">
                      <div class="">

                        </div>
                    <div class="">
                            <a class="text-light" id="header-global" href="{% url 'solicitud' %}"><h1>Centro de Cómputo</h1></a>
                    </div>
                    <div class="" id="admin-btn-container" >
                        <a href="{% url 'dashboard' %}" class="text-right align-self-end" id="admin-btn"><i class="fas fa-cog"></i></a>
                    </div>
          
                  </div>
                </div>
            </header>

            {% block nav %}

            {% endblock %}
      
          <!-- Page Content -->
          <div class="container" id="content-body">

            {% block content %}

            {% endblock %}
          </div>

          <script src="https://code.jquery.com/jquery-3.4.0.js"
          integrity="sha256-DYZMCC8HTC+QDr5QNaIcfR7VSPtcISykd+6eSmBW5qo="
          crossorigin="anonymous"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
          <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
          <script src="{% static '/plugins/fontawesome/js/all.min.js' %}"></script>
          <script src="{% static '/plugins/moment/min/moment-with-locales.min.js' %}"></script>
          <script src="{% static '/plugins/datetimepicker/build/js/tempusdominus-bootstrap-4.js' %}"></script>
          
          <script src="{% static '/js/scripts.js' %}"></script>
    <!--<script src="{% static '/bootstrap/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/bootstrap/popper.min.js' %}"></script>-->

    {% block scripts %}

    {% endblock %}
</body>
</html>

ccith_admon/templates/dash_navbar.html
<nav class="navbar navbar-expand navbar-light bg-light">
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'dashboard' %}">Dashboard </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="export_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Exportar datos
              </a>
              <div class="dropdown-menu" aria-labelledby="export_dropdown">
                
                <a class="dropdown-item" href="{% url 'exportar_csv_registros' %}">Exportar CSVs de Registros</a>
                <a class="dropdown-item" href="{% url 'exportar_csv_solicitantes' %}">Exportar CSVs de Solicitantes</a>
              </div>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.username }}
              </a>
              <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
                    {% csrf_token %}
                    <div class="dropdown">
                      <div class="dropdown-menu">
                          <button type="submit" class="dropdown-item">Cerrar Sesión</button>
                      </div>
                    </div>
                </form>
            </li>
            {% else %}
            <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>

ccith_admon/templates/dashboard.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load bootstrap %}
{% load tz %}

{% block subtitle %}
Dashboard
{% endblock %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'plugins/countdown/css/jquery.countdown.css' %}" >
{% endblock %}

{% block nav %}

{% include 'dash_navbar.html' %}

{% endblock %}

{% block content %}



{% include 'messages.html' %}



  

<div class="prestamos">

    <div class="row">
        <div class="col-lg-4 col-lg-offset-4">
            <input type="search" id="search" value="" class="form-control" placeholder="Buscar...">
        </div>
      </div>

    <div class="row">
        <div class="col-lg-4 col-lg-offset-4">
            
        </div>
      </div>
  <ul class="nav nav-tabs flex-fill justify-content-center bg-light" id="myTab" role="tablist">
      <li class="nav-item">
          <a class="nav-link active" id="all-tab" data-toggle="tab" href="#all" role="tab" aria-controls="all" aria-selected="false">Todos</a>
        </li>
  </ul>
<div class="tab-content " id="myTabContent">

    <div class="tab-pane fade show active" id="all" role="tabpanel" aria-labelledby="all-tab">
        <table class="table text-center table-hover" id="prestamo-table" cellpadding="10">
            <thead>
              <tr>
                <th scope="col">No. Registro</th>
                <th scope="col">Fecha</th>
                <th scope="col">Nombre Solicitante</th>
                <th scope="col">No. Control</th>
                <th scope="col">Carrera</th>
                <th scope="col">Razon Uso</th>
              </tr>
            </thead>
            <tbody>
              {% for registro in registros %}
              
 
                <tr class="clickable-row table-primary" data-href="#">

                  <td scope="row">{{ registro.id }}</td>
                  <td>{{ registro.fecha_hora }}</td>
                  <td>{{ registro.solicitante.nombre }} {{ registro.solicitante.ap_pat }} {{ registro.solicitante.ap_mat }}</td>
                  <td>{{ registro.solicitante.matricula }}</td>
                  <td>{{ registro.solicitante.carrera }}</td>
                  <td>{{ registro.razon_uso }}</td>
                </tr>
              
              {% endfor %}
            </tbody>
          </table>

    </div>


</div>


{% endblock %}

{% block scripts %}
<script src="{% static 'plugins/countdown/js/jquery.plugin.js' %}"></script>
<script src="{% static 'plugins/countdown/js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'plugins/jquery-searchable/jquery.searchable.js' %}"></script>

<script type="text/javascript">
  $(function () {
    $( '.table' ).searchable();
  });
</script>
<script>
  function incidencia_confirm() {
    confirm("Desea marcarlo como incidencia?");
  }
</script>

{% endblock %}

ccith_admon/templates/messages.html
{% if form.errors %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <ul>
      

        {% for error in form.non_field_errors %}

        <li>{{ error|escape }}</li>

        {% endfor %}
        {% for error,message in form.errors.items %}
        <li>Error en campo: {{ error|escape }} {{ message|escape }}</li>
        {% endfor %}
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

{% if messages %}


      {% for message in messages %}
      {% if message.tags == 'warning' %}
      <div class="alert alert-warning alert-dismissible fade show align-self-center" role="alert">
        {% elif message.tags == 'error' %}
        <div class="alert alert-danger alert-dismissible fade show align-self-center" role="alert">
        {% elif message.tags == 'success' %}
        <div class="alert alert-success alert-dismissible fade show align-self-center" role="alert">
          {% else %}
          <div class="alert alert-primary alert-dismissible fade show align-self-center" role="alert">
            {% endif %}
            <ul>
              <li>{{ message }}</li>
            </ul>
      
      
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          
        </div>
        {% endfor %}
{% endif %}

ccith_admon/templates/proyectores.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load bootstrap %}

{% block subtitle %}
Proyectores
{% endblock %}

{% block styles %}
<style>

</style>
{% endblock %}

{% block nav %}

{% include 'dash_navbar.html' %}

{% endblock %}

{% block content %}


{% include 'messages.html' %}

<h1 class="mb-5"> Proyectores </h1>

<div class="container">
        <div class="row">
        {% for proyector in todos %}
          <div class="col-lg">
           
                <div class="card text-center mb-4">
                        <div class="card-header">
                         Proyector {{ proyector.id_proyector }}
                        </div>
                        <div class="card-body">
                          <p class="card-text">{{proyector.descripcion}}</p>
                          {% if proyector.disponible %}
                          <form action ="{% url 'proyector_status_update' proyector.id_proyector %}" method="POST">
                            {% csrf_token %}
                            <input class="btn btn-warning" type="submit" name="submit" value="Marcar como No disponible" />
                          </form>
                          {% else %}
                          <form action ="{% url 'proyector_status_update' proyector.id_proyector %}" method="POST">
                                {% csrf_token %}
                                <input class="btn btn-success" type="submit" name="submit" value="Marcar como Disponible" />
                              </form>
                          {% endif %}
                        </div>
                        {% if proyector.disponible %}
                        <div class="card-footer bg-success text-light">
                          Disponible
                        </div>
                          {% else %}
                        <div class="card-footer bg-danger text-light">
                         No Disponible
                        </div>
                        {% endif %}
                        
                </div>
                
          </div>
          {% endfor %}
          
        </div>
</div>

{% endblock %}

{% block scripts %}

<script>
$('.nav.navbar-nav > li').on('click', function (e) {
    
    $('.nav.navbar-nav > li').removeClass('active');
    $(this).addClass('active');
});

</script>

{% endblock %}

ccith_admon/templates/solicitantes.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load bootstrap %}

{% block subtitle %}
Solicitantes
{% endblock %}

{% block styles %}
<style>

</style>
{% endblock %}

{% block nav %}
{% include 'dash_navbar.html' %}
{% endblock %}



{% block content %}


{% include 'messages.html' %}


<h1 class="mb-4"> Lista de Solicitantes </h1>

<div class="solicitantes">
        <div class="row">
            <div class="col-lg-4 col-lg-offset-4">
                <input type="search" id="search" value="" class="form-control" placeholder="Buscar...">
            </div>
        </div>

    <div class="row">
        <div class="col-lg-4 col-lg-offset-4">
            
        </div>
        </div>
    <ul class="nav nav-tabs flex-fill justify-content-center bg-light" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="all-tab" data-toggle="tab" href="#all" role="tab" aria-controls="all" aria-selected="false">Todos</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" id="regulares-tab" data-toggle="tab" href="#regulares" role="tab" aria-controls="regulares" aria-selected="true">Regulares</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="con_incidencias-tab" data-toggle="tab" href="#con_incidencias" role="tab" aria-controls="con_incidencias" aria-selected="true">Con Incidencias</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="bloqueados-tab" data-toggle="tab" href="#bloqueados" role="tab" aria-controls="cerrados" aria-selected="true">3 o mas Incidencias</a>
        </li>
    </ul>

    <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="all" role="tabpanel" aria-labelledby="all-tab">
                    <table class="table text-center table-hover" id="prestamo-table" cellpadding="10">
                        <thead>
                          <tr>
                            <th scope="col">Matricula</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Carrera</th>
                            <th scope="col">Bloqueado</th>
                          </tr>
                        </thead>
                        <tbody>

                        </tbody>
                        <td scope="row"></td>
                      </table>
            
                </div>
                <div class="tab-pane fade" id="regulares" role="tabpanel" aria-labelledby="regulares-tab">
                    <table class="table text-center table-hover" id="rgulares-table" cellpadding="10">
                        <thead>
                          <tr>
                            <th scope="col">Matricula</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Carrera</th>
                            <th scope="col">Bloqueado</th>
                          </tr>
                        </thead>
                        <tbody>
                                {% for regular in regulares %}
                              
                                <tr class="clickable-row table-primary" data-href="#">
                                        <td scope="row">{{ regular.matricula }}</td>
                                        <td>{{ regular.nombre}}</td>
                                        <td>{{ regular.carrera }}</td>
                                        <td>{{ regular.bloqueado }}</td>
                                        
    
                                </tr>
                              
                              {% endfor %}

                        </tbody>
                      </table>
            
                </div>
                <div class="tab-pane fade" id="con_incidencias" role="tabpanel" aria-labelledby="con_incidencias-tab">
                        <table class="table text-center table-hover" id="prestamo-table" cellpadding="10">
                            <thead>
                              <tr>
                                    <th scope="col">Matricula</th>
                                    <th scope="col">Nombre</th>
                                    <th scope="col">Carrera</th>
                                    <th scope="col">Incidencias</th>
                                    <th scope="col">Bloqueado</th>
                                    
                              </tr>
                            </thead>
                            <tbody>
                              {% for incidente in incidentes %}
                              
                                <tr class="clickable-row table-warning" data-href="#">
                                        <td scope="row">{{ incidente.matricula }}</td>
                                        <td>{{ incidente.nombre}}</td>
                                        <td>{{ incidente.carrera }}</td>
                                        <td>{{ incidentes_count.solicitante_count }}</td>
                                        <td>{{ incidente.bloqueado }}</td>
                                        
    
                                </tr>
                              
                              {% endfor %}
                            </tbody>
                          </table>
                    </div>
                    <div class="tab-pane fade show" id="bloqueados" role="tabpanel" aria-labelledby="bloqueados-tab">
                            <table class="table text-center table-hover" id="prestamo-table" cellpadding="10">
                                <thead>
                                  <tr>
                                        <th scope="col">Matricula</th>
                                        <th scope="col">Nombre</th>
                                        <th scope="col">Carrera</th>
                                        <th scope="col">Incidencias</th>
                                        <th scope="col">Bloqueado</th>
                                        <th scope="col">Bloquear</th>
                                  </tr>
                                </thead>
                                <tbody>
                                  {% for bloqueado in bloqueados %}
                                  
                                    <tr class="clickable-row table-danger" data-href="#">
                                            <td scope="row">{{ bloqueado.matricula }}</td>
                                            <td>{{ bloqueado.nombre}}</td>
                                            <td>{{ bloqueado.carrera }}</td>
                                            <td>{{ bloqueados_count.solicitante_count }}</td>
                                            <td>{{ bloqueado.bloqueado }} </td>
                                            <td>
                                            {% if bloqueado.bloqueado == False %}
                                            <form action ="{% url 'bloquear_solicitante' bloqueado.matricula %}" method="POST">
                                                    {% csrf_token %}
                                                <button class="btn btn-danger" type="submit" name="submit"><i class="fas fa-user-slash"></i></button>
                                            </form>
                                            {% else %}
                                            <form action ="{% url 'bloquear_solicitante' bloqueado.matricula %}" method="POST">
                                                    {% csrf_token %}
                                                    <button class="btn btn-primary" type="submit" name="submit"><i class="fas fa-user-check"></i></button>
                                            </form>
                                            {% endif %}
                                            </td>

        
                                    </tr>
                                  
                                  {% endfor %}
                                </tbody>
                              </table>
                        </div>

    </div>

</div>


{% endblock %}

{% block scripts %}

<script src="{% static 'plugins/jquery-searchable/jquery.searchable.js' %}"></script>

<script type="text/javascript">
  $(function () {
    $( '.table' ).searchable();
  });
</script>
<script>
    function block_confirm() {
        confirm("Desea realizar la devolucion del proyector?");
    }
</script>

{% endblock %}